name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      shell: bash
      run: |
        npm install hexo-cli -g
        npm install --force

    - name: Build
      shell: bash
      env:
        output: public
      run: |
        hexo generate
        for i in `ls -A`; do \
        if [ "$i" == ".git" ]; then continue; fi;\
        if [ "$i" == "$output" ]; then continue; fi;\
        rm -rf $i; done
        for i in `ls -A $output`; do \
        mv -t . $output/$i; done
        rmdir $output

    - name: Deploy
      shell: bash
      env:
        branch: gh-pages
      run: |
        git config --global user.name  "github-actions[bot]"
        git config --global user.email "73828441+uqbn@users.noreply.github.com"
        git config --list
        git checkout --quiet --orphan $branch
        git add --all
        git commit --quiet --signoff --message $(git rev-parse origin/master)
        git push --force origin $branch
